# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tan Gemicioglu
tagline:          ''
description:      ''
url:              https://tgemici.me
baseurl:          /

author:
  name:           'Tan Gemicioglu'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tangemicioglu/tangemicioglu.github.io

include: [_pages]